### ISSUE TITLE
有关DATA_PATH中提到的数据集缺失

### ISSUE THREAD

**Issue by 2654113847** [MKMaS-GUET/MTVAF#1]
您好，我在试图重现您的代码的时候发现，您没有提供数据集。请问DATA_PATH中提到的twitter15，twitter17，twitter2015，twitter2017数据集我该怎么获得呢？能否请您提供一个链接可以下载数据集。非常感谢您！

**Comment by 257556227** [comment]
您好，我这边已经把数据集放在Readme中，需要的可以通过链接下载，由于AUX_PATH和CAPTION_PATH在实际训练中没有使用到，因此没有提供。
